###
@BASE_URL = http://localhost

//Parte del empleado 
// get donde lista todos los empleados
###
GET {{ BASE_URL }}/EmpleadoServicio/listarEmpleados HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


/// get donde lista empleado por id*/
###
GET {{ BASE_URL }}/EmpleadoServicio/obtenerPorId?id=201 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


// post donde se crea un nuevo empleado
###
POST {{ BASE_URL }}/EmpleadoServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
 "CodigoEmpleado": "",
  "Nombre": "Berny",
  "Apellidos": "Davila",
  "Identificacion": "1-1111-1111",
  "Correo": "bernys@correo.com",
  "Telefono": "8888-8888",
  "FechaIngreso": "2026-02-08",
  "Estado": 1,
  "HoraEntrada": "08:00:00",
  "CuentaBancaria": 123456,
  "Salario": 450000,
  "idDepartamento": 1,
  "HoraSalida": "17:00:00"
}




//put para actualizar un empleado por id 
###


PUT {{ BASE_URL }}/EmpleadoServicio/actualizar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{

 "idEmpleado": 201,
  "CodigoEmpleado": "E001",
  "Nombre": "Berny",
  "Apellidos": "Aguilar",
  "Identificacion": "1-1111-1111",
  "Correo": "bernys@correo.com",
  "Telefono": "6209-7471",
  "FechaIngreso": "2026-02-08",
  "Estado": 1,
  "HoraEntrada": "08:00:00",
  "CuentaBancaria": 123456,
  "Salario": 450000,
  "idDepartamento": 1,
  "HoraSalida": "17:00:00"
}



//delete para eliminar un empleado por id
###
DELETE {{ BASE_URL }}/EmpleadoServicio/eliminar?id=405 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}






###
GET {{ BASE_URL }}/Servicio1/listar2 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}



###
POST {{ BASE_URL }}/Servicio1/listar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}







///Parte del usuario
###
GET {{ BASE_URL }}/UsuarioServicio/listarUsuarios HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


/// get donde lista usuario por id*/
###
GET {{ BASE_URL }}/UsuarioServicio/obtenerPorId?id=20 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


// post donde se crea un nuevo empleado
###
POST {{ BASE_URL }}/UsuarioServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "Nombre": "Jeeyson",
  "Apellidos": "Martinez",
  "Estado": 1,
  "FechaCreacion": "2026-02-08",
  "Clave": "password123",
  "Telefono": "8888-8888",
  "Correo": "bernys@correo.com",
  "idRol": 1,
  "idDepartamento": 2
}




//put para actualizar un usuario por id 
###


PUT {{ BASE_URL }}/UsuarioServicio/actualizar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
    "idUsuario": 20,
   "Nombre": "Jeeyson",
  "Apellidos": "Martinez",
  "Estado": 1,
  "FechaCreacion": "2026-02-08",
  "Clave": "password123",
  "Telefono": "8888-8888",
  "Correo": "bernys@correo.com",
  "idRol": 1,
  "idDepartamento": 2
}



//delete para eliminar un usuario por id
###
DELETE {{ BASE_URL }}/UsuarioServicio/eliminar?id=20 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}






///Parte del departamento
// get donde lista todos los departamentos
###
GET {{ BASE_URL }}/DepartamentoServicio/listarDepartamentos HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


/// get donde lista departamento por id*/
###
GET {{ BASE_URL }}/DepartamentoServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


// post donde se crea un nuevo departamento
###
POST {{ BASE_URL }}/DepartamentoServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "Nombre": "IT Department",
  "Descripcion": "Departamento de IT",
  "Estado": 1
}



//put para actualizar un departamento por id 
###


PUT {{ BASE_URL }}/DepartamentoServicio/actualizar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "idDepartamento": 1,
  "Nombre": "Recursos Humanos",
  "Descripcion": "Departamento de recursos humanos actualizado",
  "Estado": 1
}



//delete para eliminar un departamento por id
###
DELETE {{ BASE_URL }}/DepartamentoServicio/eliminar?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


///Parte de la planilla
// get donde lista todas las planillas
###
GET {{ BASE_URL }}/PlanillaServicio/listarPlanillas HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


/// get donde lista planilla por id*/
###
GET {{ BASE_URL }}/PlanillaServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


// post donde se crea una nueva planilla
###
POST {{ BASE_URL }}/PlanillaServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "EstadoPlanilla": "Activa",
  "Idusuario": 1,
  "Fechacreacion": "2026-02-08"
}



//put para actualizar una planilla por id 
###


PUT {{ BASE_URL }}/PlanillaServicio/actualizar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "idPlanillas": 2,
  "EstadoPlanilla": "Cerrada",
  "IdUsuario": 1,
  "Fechacreacion": "2026-02-08"
}

  

//delete para eliminar una planilla por id
###
DELETE {{ BASE_URL }}/PlanillaServicio/eliminar?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


{
  "Usuario": "root"
}


///Parte del pago
// get donde lista todos los pagos
###
GET {{ BASE_URL }}/PagoServicio/listarPagos HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


/// get donde lista pago por id*/
###
GET {{ BASE_URL }}/PagoServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


// post donde se crea un nuevo pago
###
POST {{ BASE_URL }}/PagoServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "IdPlanilla": 1,
  "IdEmpleado": 201,
  "MontoPagado": 550000.00,
  "MetodoPago": "Transferencia bancaria",
  "ReferenciaPago": "TRF-001",
  "IdUsuarioProcesa": 1,
  "FechaPago": "2026-02-08 10:00:00",
  "Estado": 1,
  "idFeriados": 1,
  "idDeduccion": 401
}



//put para actualizar un pago por id 
###


PUT {{ BASE_URL }}/PagoServicio/actualizar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "IdPago": 1,
  "IdPlanilla": 1,
  "IdEmpleado": 201,
  "MontoPagado": 650000.00,
  "MetodoPago": "Transferencia bancaria",
  "ReferenciaPago": "TRF-001",
  "IdUsuarioProcesa": 1,
  "FechaPago": "2026-02-08 10:00:00",
  "Estado": 1,
  "idFeriados": 1,
  "idDeduccion": 401
}



//delete para eliminar un pago por id
###
DELETE {{ BASE_URL }}/PagoServicio/eliminar?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


///Parte del feriado
// get donde lista todos los feriados
###
GET {{ BASE_URL }}/FeriadoServicio/listarFeriados HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


/// get donde lista feriado por id*/
###
GET {{ BASE_URL }}/FeriadoServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


// post donde se crea un nuevo feriado
###
POST {{ BASE_URL }}/FeriadoServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "Fecha": "2026-12-25 00:00:00",
  "Nombre": "Navidad",
  "EsObligatorio": 1
}



//put para actualizar un feriado por id 
###


PUT {{ BASE_URL }}/FeriadoServicio/actualizar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "IdFeriado": 14,
  "Fecha": "2026-01-01 00:00:00",
  "Nombre": "Dia del trabajador",
  "EsObligatorio": 1
}



//delete para eliminar un feriado por id
###
DELETE {{ BASE_URL }}/FeriadoServicio/eliminar?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}










//Parte de los aguinaldos

// get donde lista todos los aguinaldos
###
GET {{ BASE_URL }}/AguinaldosServicio/listarAguinaldos HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

/// get donde lista aguinaldo por id*/
###
GET {{ BASE_URL }}/AguinaldosServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

// post donde se crea un nuevo aguinaldo
###
POST {{ BASE_URL }}/AguinaldosServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json  
Origin: {{ BASE_URL }}

{
  "IdEmpleado": 201,
  "Periodo": "2026",
  "MontoCalculado": 450000.00,
  "FechaPago": "2026-02-08",
  "idUsuario": 1,
  "Estado": 1
}

//put para actualizar un aguinaldo por id
###
PUT {{ BASE_URL }}/AguinaldosServicio/actualizar HTTP/1.1 
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json  
Origin: {{ BASE_URL }}

{
  "IdAguinaldo": 1,
  "IdEmpleado": 201,
  "Periodo": "2026",
  "MontoCalculado": 550000.00,
  "FechaPago": "2026-02-08",
  "idUsuario": 1,
  "Estado": 1
}

//delete para eliminar un aguinaldo por id
### 
DELETE {{ BASE_URL }}/AguinaldosServicio/eliminar?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}




//parte del contrato

// get donde lista todos los contratos
###
GET {{ BASE_URL }}/ContratoServicio/listarContratos HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

/// get donde lista contrato por id*/
###
GET {{ BASE_URL }}/ContratoServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

// post donde se crea un nuevo contrato
###
POST {{ BASE_URL }}/ContratoServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "IdEmpleado": 201,
  "TipoContrato": "Indefinido",
  "FechaInicio": "2026-02-01",
  "FechaFin": null,
  "Salario": 450000.00,
  "Estado": 1
}

//put para actualizar un contrato por id
###
PUT {{ BASE_URL }}/ContratoServicio/actualizar HTTP/1.1 
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "IdContrato": 1,
  "IdEmpleado": 201,
  "TipoContrato": "Plazo fijo",
  "FechaInicio": "2026-02-01",
  "FechaFin": "2027-02-01",
  "Salario": 500000.00,
  "Estado": 1
}

//delete para eliminar un contrato por id
### 
DELETE {{ BASE_URL }}/ContratoServicio/eliminar?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


///Parte de prestamo
// get donde lista todos los prestamos
###
GET {{ BASE_URL }}/PrestamoServicio/listarPrestamos HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


/// get donde lista prestamo por id*/
###
GET {{ BASE_URL }}/PrestamoServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


// post donde se crea un nuevo prestamo
###
POST {{ BASE_URL }}/PrestamoServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "IdEmpleado": 201,
  "MontoTotal": 1000000,
  "Cuotas": 12,
  "MontoPorCuota": 83333.33,
  "SaldoPendiente": 1000000,
  "FechaInicio": "2026-02-10",
  "Estado": "1",
  "IdUsuario": 1
}




//put para actualizar un prestamo por id 
###


PUT {{ BASE_URL }}/PrestamoServicio/actualizar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "IdPrestamo": 1,
  "IdEmpleado": 201,
  "MontoTotal": 1000000,
  "Cuotas": 12,
  "MontoPorCuota": 83333.33,
  "SaldoPendiente": 500000,
  "FechaInicio": "2026-02-10",
  "Estado": "1",
  "IdUsuario": 1
}



//delete para eliminar un prestamo por id
###
DELETE {{ BASE_URL }}/PrestamoServicio/eliminar?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

///Parte de detalleplanilla
// get donde lista todos los detalleplanilla
###
GET {{ BASE_URL }}/DetalleplanillaServicio/listarDetalleplanilla HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


/// get donde lista detalleplanilla por id*/
###
GET {{ BASE_URL }}/DetalleplanillaServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


// post donde se crea un nuevo detalleplanilla
###
POST {{ BASE_URL }}/DetalleplanillaServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "SalarioBase": 450000,
  "HorasExtra": "02:30:00",
  "Deducciones": 50000,
  "Bono": 25000,
  "TotalDeducciones": 50000,
  "SalarioNeto": 425000,
  "SalarioBruto": 475000,
  "idPlanilla": 1
}




//put para actualizar un detalleplanilla por id 
###


PUT {{ BASE_URL }}/DetalleplanillaServicio/actualizar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "idDetallePlanilla": 1,
  "SalarioBase": 450000,
  "HorasExtra": "03:00:00",
  "Deducciones": 50000,
  "Bono": 30000,
  "TotalDeducciones": 50000,
  "SalarioNeto": 430000,
  "SalarioBruto": 480000,
  "idPlanilla": 1
}



//delete para eliminar un detalleplanilla por id
###
DELETE {{ BASE_URL }}/DetalleplanillaServicio/eliminar?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}



///Parte del control de asistencia

// get donde lista todos los controlAsistencia
###
GET {{ BASE_URL }}/ControlAsistenciaServicio/listarControlAsistencia HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

 // get donde lista controlAsistencia por id*/
###
GET {{ BASE_URL }}/ControlAsistenciaServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

// post donde se crea un nuevo controlAsistencia
###
POST {{ BASE_URL }}/ControlAsistenciaServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
 
  "HoraEntrada": "08:00:00",
  "HoraSalida": "17:00:00",
  "IdEmpleado": 201,
  "idUsuarios": 1
}

//put para actualizar un controlAsistencia por id
###
PUT {{ BASE_URL }}/ControlAsistenciaServicio/actualizar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "IdControlAsistencia": 1,
  "HoraEntrada": "08:30:00",
  "HoraSalida": "17:30:00",
  "IdEmpleado": 202,
  "idUsuarios": 1
}

//delete para eliminar un controlAsistencia por id
###
DELETE {{ BASE_URL }}/ControlAsistenciaServicio/eliminar?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}







//Parte del control de horarios

// get donde lista todos los controlHorarios
###
GET {{ BASE_URL }}/ControlHorarioServicio/listarControlHorario HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

 // get donde lista controlHorarios por id*/
###
GET {{ BASE_URL }}/ControlHorarioServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json  
Origin: {{ BASE_URL }}

// post donde se crea un nuevo controlHorarios
###
POST {{ BASE_URL }}/ControlHorarioServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "IdEmpleado": 201,
  "Fecha": "2024-01-01",
  "HoraEntrada": "08:00:00",
  "HoraSalida": "17:00:00",
  "HorasNormales": "08:00:00",
  "HorasExtra": "00:00:00",
  "Estado": 1,
  "idUsuarios": 1
}

//put para actualizar un controlHorarios por id
###
PUT {{ BASE_URL }}/ControlHorarioServicio/actualizar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "IdControl": 2,
  "IdEmpleado": 201,
  "Fecha": "2024-01-01",
  "HoraEntrada": "08:30:00",
  "HoraSalida": "17:30:00",
  "HorasNormales": "08:00:00",
  "HorasExtra": "00:00:00",
  "Estado": 1,
  "idUsuarios": 1
}

//delete para eliminar un controlHorarios por id
###
DELETE {{ BASE_URL }}/ControlHorarioServicio/eliminar?id=1 HTTP/1.1
Authorization: Bearer {{ BASE_URL }}
Content-Type: application/json
Origin: {{ BASE_URL }}





//Parte de las deducciones

// get donde lista todos los deducciones
###
GET {{ BASE_URL }}/DeduccionesServicio/listarDeducciones HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

 // get donde lista deducciones por id*/
###
GET {{ BASE_URL }}/DeduccionesServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

// post donde se crea un nuevo deducciones
###
POST {{ BASE_URL }}/DeduccionesServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "Nombre": "Seguro social",
  "Monto": 50000.00,
  "Impuesto": 0.00,
  "Estado": 1,
  "idEmpleado": 201,
  "usuariosId": 1,
  "idPrestamo": null
  
}

//put para actualizar un deducciones por id
### 
PUT {{ BASE_URL }}/DeduccionesServicio/actualizar HTTP/1.1  
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "idDeducciones": 601,
  "Nombre": "Seguro social actualizado",
  "Monto": 60000.00,
  "Impuesto": 0.00,
  "Estado": 1,
  "idEmpleado": 201,
  "usuariosId": 1,
  "idPrestamo": null
}

//delete para eliminar un deducciones por id
###
DELETE {{ BASE_URL }}/DeduccionesServicio/eliminar?id=601 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}




//Parte del historial de salarios

// get donde lista todos los historialSalarios
###
GET {{ BASE_URL }}/HistorialSalarioServicio/listarHistorialSalario HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

 // get donde lista historialSalarios por id*/
###
GET {{ BASE_URL }}/HistorialSalarioServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

// post donde se crea un nuevo historialSalarios
###
POST {{ BASE_URL }}/HistorialSalarioServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


{
  "MontoSalario": 500000,
  "FechaInicio": "2026-02-01",
  "FechaFin": "2026-12-31",
  "MotivoCambio": "Aumento salarial",
  "idUsuarios": 1,
  "idEmpleados": 204
}



//put para actualizar un historialSalarios por id
###
PUT {{ BASE_URL }}/HistorialSalarioServicio/actualizar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


{
  "idHistorialSalarios": 201,
  "MontoSalario": 550000,
  "FechaInicio": "2026-02-01",
  "FechaFin": "2026-12-31",
  "MotivoCambio": "Aumento por desempeño",
  "idUsuarios": 1,
  "idEmpleados": 204
}



//delete para eliminar un historialSalarios por id
###
DELETE {{ BASE_URL }}/HistorialSalarioServicio/eliminar?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}



//Parte de las licencias

// get donde lista todos los licencias
###
GET {{ BASE_URL }}/LicenciaServicio/listarLicencia HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

 // get donde lista licencias por id*/  
###
GET {{ BASE_URL }}/LicenciaServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

// post donde se crea un nuevo licencias
###
POST {{ BASE_URL }}/LicenciaServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "IdEmpleado": 201,
  "Tipo": "Incapacidad médica",
  "FechaInicio": "2026-02-05",
  "FechaFin": "2026-02-10",
  "DocumentoSoporte": "incapacidad_201.pdf",
  "Estado": 1,
  "idUsuario": 1
}
//put para actualizar un licencias por id
###
PUT {{ BASE_URL }}/LicenciaServicio/actualizar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
 "IdLicencia": 37,
  "IdEmpleado": 201,
  "Tipo": "Licencia personal",
  "FechaInicio": "2026-02-05",
  "FechaFin": "2026-02-12",
  "DocumentoSoporte": "licencia_actualizada.pdf",
  "Estado": 1,
  "idUsuario": 1
}

//delete para eliminar un licencias por id
###
DELETE {{ BASE_URL }}/LicenciaServicio/eliminar?id=37 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json  
Origin: {{ BASE_URL }}


//Parte del periodo de planilla
// get donde lista todos los periodoPlanilla
### 
GET {{ BASE_URL }}/PeriodoPlanillaServicio/listarPeriodoPlanilla HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

 // get donde lista periodoPlanilla por id*/
###
GET {{ BASE_URL }}/PeriodoPlanillaServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

// post donde se crea un nuevo periodoPlanilla
###
POST {{ BASE_URL }}/PeriodoPlanillaServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "NombrePeriodo": "Quincena 1 - Febrero 2026",
  "FechaInicio": "2026-02-01",
  "FechaFin": "2026-02-15"
}

//put para actualizar un periodoPlanilla por id
###
PUT {{ BASE_URL }}/PeriodoPlanillaServicio/actualizar HTTP/1.1  
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "idPeriodoPlanilla": 13,
  "NombrePeriodo": "Quincena 1 - Febrero 2026 (Editado)",
  "FechaInicio": "2026-02-01",
  "FechaFin": "2026-02-15"
}

//delete para eliminar un periodoPlanilla por id
###
DELETE {{ BASE_URL }}/PeriodoPlanillaServicio/eliminar?id=13 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

///Parte de puestos
// get donde lista todos los puestos
###
GET {{ BASE_URL }}/PuestosServicio/listarPuestos HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


/// get donde lista puestos por id*/
###
GET {{ BASE_URL }}/PuestosServicio/obtenerPorId?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}


// post donde se crea un nuevo puesto
###
POST {{ BASE_URL }}/PuestosServicio/insertar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "NombrePuesto": "Desarrollador Senior",
  "Descripcion": "Responsable de desarrollo de software",
  "SalarioBase": 800000,
  "Estado": 1,
  "idEmpleado": 202,
  "idUsuario": 1
}




//put para actualizar un puesto por id 
###


PUT {{ BASE_URL }}/PuestosServicio/actualizar HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}

{
  "IdPuestos": 1,
  "NombrePuesto": "Desarrollador Senior",
  "Descripcion": "Responsable senior del desarrollo de software",
  "SalariosBase": 850000,
  "Estado": 1,
  "idEmpleado": 201,
  "idUsuario": 1
}



//delete para eliminar un puesto por id
###
DELETE {{ BASE_URL }}/PuestosServicio/eliminar?id=1 HTTP/1.1
Authorization: Bearer {{ AUTH_TOKEN }}
Content-Type: application/json
Origin: {{ BASE_URL }}